---
- name: update
  package:
    update_cache: true
  tags:
    - update apt

- name: NGINX | Install NGINX
  package:
    name: nginx
    state: latest
  notify:
    - restart nginx
  tags:
    - nginx-package

- name: NGINX | Create NGINX config file from template
  template:
    src: NGINX/templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify:
    - reload nginx
  tags:
    - nginx_configuration
...